@startuml C3 - Novo - Order Service API
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(cliente, "Cliente")
ContainerDb(mongo_analitics, "Cold Database", "MongoDB Analytics Node", "Armazena ordens de compra")

System_Boundary(b_order_service, "Order Service") {
    Container(order_controller, "Order Controller", "Java, SpringBoot", "Recebe requisição dos clientes")
    Container(order_service, "Order Service", "Java, SpringBoot", "Centraliza o processamento e chama a classe de repository")
    Container(order_repository, "Order Repository", "Java, SpringBoot", "Centraliza todos os metodos que fazem interface com o DB")
}

Rel(cliente,order_controller, "Envia request com informações de conta", "HTTPS")
Rel(order_controller,order_service, "Envia requisição para processamento")
Rel(order_service,order_repository, "Envia requisição para camada de DB")
Rel(order_repository,mongo_analitics, "Executa busca no DB")






